include lib/main.mk

lib/main.mk:
ifneq (,$(shell git submodule status lib 2>/dev/null))
	git submodule sync
	git submodule update --init
else
	echo "A template for IETF internet draft git repositories is missing..."
	exit 1
endif